version: "2"
services:

    avahi-daemon:
        image: tukiyo3/avahi-daemon:latest
        network_mode: host
        restart: always
        networks:
            - proxy

    cloudflare:
        image: cloudflare/cloudflared:latest
        container_name: cloudflare
        restart: unless-stopped
        command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}"
        networks:
            - proxy

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./files/nginx-proxy/conf.d/local.conf:/etc/nginx/conf.d/local.conf
            - ./data/nginx-proxy/vhost.d:/etc/nginx/vhost.d
            - ./data/nginx-proxy/html:/usr/share/nginx/html
            - ./data/nginx-proxy/certs:/etc/nginx/certs
        dns:
            - 127.0.0.1
        networks:
            - proxy

    nginx-proxy-acme:
        image: nginxproxy/acme-companion
        container_name: nginx-proxy-acme
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/nginx-proxy/vhost.d:/etc/nginx/vhost.d
            - ./data/nginx-proxy/html:/usr/share/nginx/html
            - ./data/nginx-proxy/certs:/etc/nginx/certs
            - ./data/nginx-proxy/acme:/etc/acme.sh
        environment:
            - "DEFAULT_EMAIL=${DEFAULT_EMAIL}"
        volumes_from:
            - nginx-proxy
        networks:
            - proxy

    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        restart: unless-stopped
        environment:
            - "PUID=1000"
            - "PGID=1000"
            - "TZ=Europe/Paris"
            - "VIRTUAL_HOST=duplicati.home.sds.ovh duplicati.local"
            - "VIRTUAL_PORT=8200"
            - "LETSENCRYPT_HOST=duplicati.home.sds.ovh"
        volumes:
            - ./data/duplicati/appdata/config:/config
            - ./data:/files
        ports:
            - "8200:8200"
        networks:
            - proxy

networks:
    proxy: