version: "3"
services:

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        #            - ./data/nginx-proxy/certs:/etc/nginx/certs:ro
        #            - ./data/nginx-proxy/vhost.d:/etc/nginx/vhost.d
        #            - ./data/nginx-proxy/html:/usr/share/nginx/html
        restart: unless-stopped

    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
        volumes:
            - ./data/duplicati/appdata/config:/config
            - ./data:/files
        ports:
            - "8200:8200"
        restart: unless-stopped
