version: "3"
services:

    cloudflare:
        image: cloudflare/cloudflared:latest
        container_name: cloudflare
        restart: unless-stopped
        environment:
            - "tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}"
        networks:
            - proxy

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./files/nginx-proxy/conf.d/local.conf:/etc/nginx/conf.d/local.conf
        dns:
            - 127.0.0.1
        networks:
            - proxy

    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        restart: unless-stopped
        environment:
            - "PUID=1000"
            - "PGID=1000"
            - "TZ=Europe/Paris"
            - "VIRTUAL_HOST=duplicati.home.local"
            - "VIRTUAL_PORT=8200"
#            - LETSENCRYPT_HOST=duplicati.home.local
        volumes:
            - ./data/duplicati/appdata/config:/config
            - ./data:/files
        ports:
            - "8200:8200"
        networks:
            - proxy

networks:
    proxy: